#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO


#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_TERM
#define TAPPING_TERM 0

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1

#define COMBO_TERM 10

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "danr9/EeNp5Q"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

